### ISSUE TITLE
Cabal version check fails

### ISSUE THREAD

**Issue by bat-tsagan** [cleary/ansible-tidalcycles#17]
Hi, I'm trying to install the VSCode ansible version and at the point where it gets the cabal version it failswith the following output:

TASK [roles/tidal : get cabal version] ********************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "cabal --numeric-version", "delta": "0:00:00.002904", "end": "2023-01-27 18:34:05.578829", "msg": "non-zero return code", "rc": 127, "start": "2023-01-27 18:34:05.575925", "stderr": "/bin/sh: 1: cabal: not found", "stderr_lines": ["/bin/sh: 1: cabal: not found"], "stdout": "", "stdout_lines": []}

PLAY RECAP ************************************************************************************************************

I have the Haskell toolchain installed including GHC version 9.2.5 and Cabal version 3.6.2.0.

My OS is elementary OS 6.1 Jólnir (based on Ubuntu 20.04).

**Comment by cleary** [comment]
Hi, it sounds like you're working off a lot of non-standard packaging items which this tool isn't designed to support (with this, start clean and get a vanilla tidal/sc install with repo provided packages).

However, what I'd recommend is editing the vscode playbook, and commenting/removing the `tidal` role so it will only do the vscode install for you, bypassing all the tidal/sc/Haskell install tasks

**Comment by bat-tsagan** [comment]
Seems pretty standard to me, installed all the Haskell components from the Haskell repos and GHCUP indicates I'm at the recommended versions. Also, where the Ansible script fails running "cabal --numeric-version", running the same thing directly at a bash prompt produces the desired result. I think I may try the manual route of installing Tidal as I can re-install my system from scratch quite easily (I deliberately decided to install Tidal first because from past experience it's a ***** to get working).

PS. To clarify that last remark,I mean working without ending up with a monumental amount of cruft in your system that affects performance.

**Comment by cleary** [comment]
Sorry, by "standard" I'm referring to out-of-the-box repos (Ubuntu standard repos).
Yes I could support the Haskell repos, or one of a bunch of ppas - but, in order to provide breadth of support across distro I'm not taking that route.

Yes it's a pain to install, which is why I built this tool - start with a blank system, and just run a playbook. There is no need to install any other packages beforehand (besides git and ansible).

I haven't explicitly tested elementary os either, so depending on where they've diverged from Ubuntu may also be the issue. Dunno, but I can only rest/support so many distros 😅
